version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - mallang

  mallang:
    image: iantoo2/mallang:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://3.38.103.249:3306/chill
      - SPRING_DATASOURCE_USERNAME=chill
      - SPRING_DATASOURCE_PASSWORD=ssafy1!
    networks:
      - app-network

networks:
  app-network:

volumes:
  mariadb_data:
